# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  # using major version aliases
  - 7.0

before_script:
  - GITHUB_NAME=mikewazovzky
  - PACKAGE_NAME=adjustable
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require $GITHUB_NAME/$PACKAGE_NAME dev-master
  - composer require satooshi/php-coveralls
  - cp ./vendor/$GITHUB_NAME/$PACKAGE_NAME/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/$GITHUB_NAME/$PACKAGE_NAME/tests/config/app.php ./config
  # rm ./tests/TestCase.php
  - cp ./vendor/$GITHUB_NAME/$PACKAGE_NAME/tests/Dummy.php ./tests
  # cp ./vendor/$GITHUB_NAME/$PACKAGE_NAME/tests/config/functions.php ./tests
  - cp ./vendor/$GITHUB_NAME/$PACKAGE_NAME/tests/config/composer_autoload.php ./
  - php composer_autoload.php
  - composer dump-autoload
  - cd ./vendor/$GITHUB_NAME/$PACKAGE_NAME
  - mkdir -p build/logs

script:
  - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
- travis_retry php ../../../vendor/bin/coveralls
